---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 99
    commit-message:
      prefix: "CHORE: "
    reviewers:
      - kimchelly
