---
linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert

linters-settings:
  govet:
    check-shadowing: false
